### ISSUE TITLE
Latest

### ISSUE THREAD

**Issue by ENikS** [MyHomeLibrary/MyHomeLib#1]
@OleksiyPenkov 

Could you merge changes from your repo into this one?

I’ve got this repo merged from the original svc server including most of the history.

**Comment by ENikS** [comment]
@OleksiyPenkov 

Ты же понимаешь по басурмански, или лучше на русском?

**Comment by OleksiyPenkov** [comment]
Можно и на русском.

**Comment by ENikS** [comment]
Я добавил `develop`, для PR

Свисти, если что то нужно от меня.
